# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/jingtao910429/2BossSpecs.git'

target 'RxWebClientExample' do

    use_frameworks!
    pod 'RxWebClient'
    
end
