# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/jingtao910429/2BossSpecs.git'

target 'RxWebClientExample' do

#    pod 'RongCloudIMManager'

    use_frameworks!
#    pod 'RxWebClient'
    pod 'Alamofire', '~> 4.3'
    pod 'Moya', '~> 11.0'
    pod 'Moya/RxSwift'
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
    pod 'SwiftyJSON', '~> 3.1.4'
    pod 'ObjectMapper', '~> 2.0.0'

end
